name: i-rochiño
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
exclude: [vendor] #Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
gems:
  - jekyll-sitemap
  - jekyll-pdf
collections:
  som:
    output : true
    permalink : /som/:path/
  montaxe:
    output : true
    permalink : /montaxe/:path/
  planificar:
    output : true
    permalink : /planificar/:path/
  entradaSaida:
    output : true
    permalink : /entradaSaida/:path/
  memoria:
    output : true
    permalink : /memoria/:path/
  placa:
    output : true
    permalink : /placa/:path/
  codificar:
    output : true
    permalink : /codificar/:path/
  perifericos:
    output : true
    permalink : /perifericos/:path/

    # FIXME definir aquí a coleción: o novo apartado que vou meter
